name: build
on: [push, pull_request]
jobs:
    windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: "recursive"
                lfs: true
            
            - uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '10.0.202'
                include-prerelease: True

            - run: 'buildwindows.cmd'
              shell: cmd

            - uses: actions/upload-artifact@v4
              with:
                name: StaticWiki-Windows
                path: ./build

    linux:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: "recursive"
                lfs: true
            
            - uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '10.0.202'
                include-prerelease: True

            - run: 'sudo apt update'

            - run: 'sudo apt install git build-essential libxi-dev libxinerama-dev libxrandr-dev libxcursor-dev libgl1-mesa-dev libx11-dev libgtk-3-dev'

            - run: 'sh buildlinux.sh'

            - uses: actions/upload-artifact@v4
              with:
                name: StaticWiki-Linux
                path: ./build
